version: "3.8"
services:
  nginx:
    image: nginx
    healthcheck:
      test: ["CMD", "service", "nginx", "status", "|| exit 1"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 1m
    deploy:
      mode: global
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
    configs:
      - source: my_conf
        target: /etc/nginx/conf.d/default.conf
    ports:
      - 443:443
      - 8080:80
    networks:
      - myNetwork
    depends_on:
      - postgres
  postgres:
    image: postgres
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      placement:
        constraints:
          - node.labels.DB == true
    volumes:
      - ~/DB_folder:/var/lib/postgresql/data
    ports:
      - 5432:5432
    secrets:
      - source: secret_psg.env
        target: /secret.env
    networks:
      - myNetwork
    environment:
      PGPASSFILE: /secret.env

networks:
  myNetwork:
    driver: overlay

secrets:
  secret_psg.env:
    external: true

configs:
  my_conf:
    external: true
